### ISSUE TITLE
Train set and test set

### ISSUE THREAD

**Issue by yinghuozijin** [hasamkhalid/FakeAVCeleb#2]
I noticed that you didn't split the train set and test set for this dataset.And I think it's necessary so that researchers can make the benchmark.
What's more, I adivse you add some real videos from Voxceleb dataset for the balance between positve and negative samples.

**Comment by hasamkhalid** [comment]
Thank you for your suggestion. Yes you are right, we should split the train/test set and provide with the dataset. I will talk with my team and bring the dataset version with train/test split.
Also, we cannot provide more real videos from VoxCeleb since Voxceleb have majority of non-english speaking people for races other than Caucasian. Plus there will not be any deepfake videos of those new videos/persons. We have kept it the person's choice they can choose more videos from VoxCeleb dataset according to their need.

Thank you.
