### ISSUE TITLE
Explain the need for images and how I might be able to offer them from the available dataset when training

### ISSUE THREAD

**Issue by x0axz** [hasamkhalid/FakeAVCeleb#3]
Hello, I asked for access to the dataset and was granted it. I now want to train the model, but I'm having trouble since I keep receiving errors telling me that I need to upload images to the Video Directory. In fact, I'm a little perplexed because the model must accept video and audio as inputs before determining whether the inputs are synthetic or not.

Could you please clarify the demand for images and how I might be able to offer them from the dataset at hand.

Please guide me. Regards

`!python train_main.py -m=MESO4 -v=FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/ -a=FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/`

```
GPU num is 0
('VIDEO', 'AUDIO')
Traceback (most recent call last):
  File "train_main.py", line 28, in <module>
    Train_MesoNet.TrainMesoNet(args)
  File "/content/FakeAVCeleb/Unimodal/Training/Train_MesoNet.py", line 61, in TrainMesoNet
    transform=train_transforms)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py", line 256, in __init__
    is_valid_file=is_valid_file)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py", line 132, in __init__
    raise RuntimeError(msg)
RuntimeError: Found 0 files in subfolders of: videos
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp
```

**Comment by hasamkhalid** [comment]
I have read your concern and I would suggest you read our papers mentioned below. You will find the information related to experimentation. 

- [**FakeAVCeleb: A Novel Audio-Video MultimodalDeepfake Dataset** ](https://openreview.net/pdf?id=TAXFsg6ZaOl) 
- [**Evaluation of an Audio-Video Multimodal Deepfake Dataset using Unimodal and Multimodal Detectors**](https://dl.acm.org/doi/abs/10.1145/3476099.3484315)

Moreover, I will explain the preprocessing steps below as well. 
I hope the questions and answers to the questions will be helpful to you:

**Q1: how did you split the data in the train test split?
Q2: how do you deal with the Data Imbalance issue while training the models?**

There are two ways of dealing with this data imbalance issue. I will explain both below:

I. To run experiments in both of our papers, we performed frame-level detection.
The number of frames extracted from Real videos was more than the number of frames extracted from Fake videos (Category B, C, D).
For example, we have 500 Real videos and around 10,000 videos in Category C and D.
So, we extracted 120 frames from Real videos : 120 x 500 = 60,000 Frames.
And we extracted 6 frames from Fake videos : 6 x 10,000 = 60,000 Frames.
By extracting frames this way, we got rid of the data imbalance issue.

II. There is another way of coping with the data imbalance issue that we briefly mentioned in the papers as well.
Since we collected Real videos from the VoxCeleb-2 dataset, the VoxCeleb dataset contains around a million Real videos.
As we have fewer Real videos in our FakeAVCeleb dataset, to get rid of the data imbalance issue we can get more
Real videos from the VoxCeleb dataset to train our models and run our experiments.
Also, we have provided the actual ids of the persons that we selected from the VoxCeleb dataset and selected a single video per person,
we can easily select more videos of the same person from the VoxCeleb dataset.

**Comment by x0axz** [comment]
I followed the instructions by splitting the video into 10 frames per second and then entered that information into the model, but it still gives me an error saying "Found 0 files in subfolders of: data/images," despite the fact that there are only images in that folder.

I changed the image extension, looked at the code, and changed the model, but the error persisted.
